POST http://localhost:3000/users/
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "username": "John1990",
    "password": "123446780"
}

###

GET http://localhost:3000/users/1

###

PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "email": "jhon1@gmail.com"
}

###

DELETE http://localhost:3000/users/1

###

curl 
    -v 
    --cookie "jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzA3MDU5ODQ2LCJleHAiOjE3MDc2NjQ2NDZ9.jfiEbB3tk2KduaKR64hi1xyIbtfAHxyX1pJ-2Rv70Zo" 
    -X DELETE
    http://localhost:3000/users/2