POST http://localhost:3000/users/
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "username": "John1990",
    "password": "123446780"
}

###

GET http://localhost:3000/users/1

###

PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "email": "jhon1@gmail.com"
}

###

DELETE http://localhost:3000/users/1